package civilization.objects

object S {

  final val numberofArmies = "numberofArmies"
  final val numberofScouts = "numberofScouts"
  final val orientation = "orientation"
  final val civ = "civ"
  final val tech = "tech"
  final val tilename = "tname"
  final val squares = "squares"
  final val row = "row"
  final val col = "col"
  final val hutvillage = "hv"
  final val resource = "resource"
  final val hutvillages = "hutvillages"
  final val hutvillagesused = "hutvillagesused"
  final val city = "city"
  final val citytype = "citytype"
  final val players = "players"
  final val map = "map"
  final val market = "market"
  final val p = "p"
  final val param = "param"
  final val trade = "trade"
  final val command = "command"
  final val figures = "f"
  final val version = "version"
  final val createtime = "createtime"
  final val accesstime = "accesstime"
  final val desc = "desc"
  final val gameid = "gameid"
  final val terrain = "terrain"
}
