package civilization

import io.readdir.TranslateMessage.translateMessage

package object message {

  object M extends Enumeration {
    type M = Value
    val POINTOUTSIDEBOARD, POINTONHIDDENTILE, POINTONWATER, CITYONWATER, POINTONBORDER,
    POINTISBORDERINGWITHHUTORVIALLAGE, CITYISBORDERINGWITHANOTHER, CAPITALALREADYBUILD, CITYLIMITEXCEEDED,
    NOUNUSEDHUTORVILLAGES, TILEALREADYREVEALED, NOTIMPLEMENTEDYET, CANNOTPUTFIGUREONWATER, STACKINGSIZEEXCEEDED,
    CANNOTSETFIGUREONCITY, NOTCITY, ONLYONESCIUTALLOWED, CANNOTGIVECOSTFORTHISOBJECT, CANNOTAFFORDOBJECT,
    LIMITFORARMIESEXCEEDED, LIMITFORSCOUTSEXCEEDED, ACTIONCANNOTBEEXECUTEDINTHISPHASE, DUPLICATECITYACTIONINTHISCITY,
    NOFIGURESBELONGINGTOCIVILIZATION, NUMBEROFSCOUTSLESS, NUMBEROFARMIESLESS, FIGURESMOVEDAGAIN, CANNOTFINDSTARTOFMOVE, TRAVELSPEEDEXCEEDED,
    CANNOTCROSSWATER, POINTNOTREVEALED, CANNOTSTOPINCITY, CANNOTSTOPINWATER, MOVENOTCONSECUTIVE, LASTMOVENOTENDED, CANNOTREVEALFROMTHISPOINT,
    TECHNOLOGYRESEARCHEDALREADY, CANNOTAFFORDTHISTECHNOLOGY, NOPLACEINTECHNOLOGYTREE, CANNOTRESEARCHMORETHENONCEINSINGLETURN, SHOULDBEDNFOFMOVENOW,
    MORECIVTTILESTHENCIVDECLARED, CANNOTFINDHOMETILEFORCIV, TOOMANYCIVREQUESTED, ITEMIZEACTIONNOTIMPLEMENTEDYET, THEREISNOCIVLIZATIONCITYATTHISPOINT,
    CITYSHOULDBEBUILDONSCOUT, HUTORVILLAGEATCITYOUTSKIRTS, FOREIGNFIGURESATCITYOUTSKIRTS, CANNOTSETFIGUREONALIENCIV, CANNOTSETFGUREONALIENCITY,
    NOTENOUGHTRADETOSPENDFORPROD, NOSCOUTATTHISPOINT, CANNOTSENTPRODTWICESCOUT, SCOUTISONCITYOUTSKIRT, CANNOTSETFIGUREONHUT, CANNOTSETFIGUREONVILLAGE,
    ALLUNITSUSED, COMMANDPARAMETERDOESNOTMATCH, THEREISNOHUTATRHISPOINT, SCOUTCANNOTEXPLOREHUT, CANNOTFINDFIGUREONATTACKINGSQUARE,
    CANNOTATTACKOWNFIGURE, CANNOTFINFANYTHINGONTHEQUARETOATTACK, CANNOTATTACKOWNCITY, CANNOTREMOVEUNITS, CANNOTUSERIRONNOW,
    IMPROPERUNITNUMBERTOPLAY, IMPROPERNUMBERTOPLAYUNIT, THEREISANOTHERUNITPLAYEDHERE, ENDOFBATTLEALREADY, BATTLEISNOTFINISHED,
    ENDOFBATTLEIMPLEMENTEDONLYFORVILLAGES, IMPROPERLOOTCANNOTGETTHISFROMLOSER, CAPITALCANBEBUILDONLYONHOMETILE,
    CANNOTBUYBUILDINGHERE, CANNOTBUYWONDERGHERE, NOTENOUGHTRADETOSPEND, NOTENOUGHVULTURETOSPEND,
    CANNOTDEVOUTTHICCITYFORCULTURE, NOTENOUGHRESOURCETOUSETECHNOLOGY,
    CANNOTSENTCLUTUREFROMSCOUT, CULTURELEVELEXCCEED, CANNOTAFFORDADVANCECULTURE, CANNOTFINDHUTVILLAGEINPLAYERDECK,
    CANNOTFINDTECHNOLOGYINPLAYERDECK, INCORRECTRESOURCEUSED, RESOURCEALREADYUSEDORCITYAGAIN, CULTURECARDNOTINPLAYERHAND,
    CANNOTPUTGREATPERSONHERE, IMPROPERACTIONTOCALCULATECOST, CITYALREADYWALLED, YOUARENOTENTITLETOSAVEUNIT,
    VILLAGEISNOTENTITLEDFORUNITTAKING, YOUALREADYSAVEUNIT, SAVEDUNITINDEXOUTOFRANGE, CANNOTTAKEFREERESOURCE,
    RESOURCENOTAVAILABLE, CANNOTSACRIFICEFIGUREFORFREETECH, YOUARENOTENTITLETORECEIVEFREERESOURCES,
    FREERESOURCESONLYATTHEBEGINNINGOFTHEGAME, CANNOTSPENDSILKFORTRADE, TOSPENDSILKONTRADEYOUHAVETOPINTOTHERCIV,
    YOUCANNOTSPENDSECONDSILKONYOUSELF, ENDOFPHASEALLOWEDFORONLY, THEPLAYERALREADYCOMPLETEDPHASE,
    NOTPLAYERTURNTOENDOFPHASE, TECHNOLOGYUSEDALREADYINTHISTURN, COINSCAPACITYEXCEEDED, EXPECTEDCITYACTIONTOBECANCELED,
    CANNOTCANCELRESOURCEABILITY, NOTALLOWEDINTHISPHASE, ONLYLASTCOMMANDCANHAVESUPENDEDSTATUS, EXPECTEDSUSPENEDCOMMAND,
    THISCOMMANDCANBEONLYINEXECUTEDMODE, CANNOTGETFREEFIGUREHANGINGGARDENINFIRSTTURN, HANGINGGARDENWONDERNOTAVAILABLE,
    COMMANDUSEDALREADYINTHISTURN = Value
  }

  case class Mess(val m: M.M, val o: AnyRef = null)

  case class FatalError(val m: Mess) extends Exception(translateMessage((m)))

  object J extends Enumeration {
    type J = Value
    val PUTCOINAFTERBATTLE, CANNOTADDCOINLIMIT, COINADDEDALREDYINTHISTURN, ATTACKWITHIRON, FIGURESAREKILLED,
    YOUARERECEIVINGFREEGREATPERSON, YOUARERECEIVING2FREEINFANTRYUNITS, YOUARERECEIVINGFREERESOURCESFROMMARKET,
    YOUARERECEIVINGSTARTINGTECHNOLOGY, DOACTION = Value
  }

}
